/* Shanghai Disneyland — Rain & Height Fear Guide
   Данные синтезированы из трёх аналитических отчётов (см. fun-trip/README.md)
   и дополнены справочными фактами (высота трека TRON, высота подъёма Soaring и т.д.).
   Изображения — локально сгенерированные SVG-плейсхолдеры (см. placeholder() в app.js),
   так как у нас нет прав на хотлинк официальных фото Disney. */

const ZONE_ORDER = [
  "Mickey Avenue",
  "Gardens of Imagination",
  "Fantasyland",
  "Treasure Cove",
  "Adventure Isle",
  "Zootopia",
  "Toy Story Land",
  "Tomorrowland"
];

const ZONE_COLORS = {
  "Mickey Avenue": ["#ffb6d9", "#ff8fc6"],
  "Gardens of Imagination": ["#c9a8ff", "#8e6bff"],
  "Fantasyland": ["#ff9ad5", "#7c4dff"],
  "Treasure Cove": ["#36c6c0", "#0e7e8c"],
  "Adventure Isle": ["#5fd16f", "#1f8a4c"],
  "Zootopia": ["#ffd166", "#ff8a3d"],
  "Toy Story Land": ["#ff7a59", "#ff4d4d"],
  "Tomorrowland": ["#5ec8ff", "#3a5bff"]
};

/**
 * recommendation: 'go' | 'caution' | 'dpa-only' | 'skip'
 * rainStatus: 'yes' | 'no' | 'partial'
 * flags: визуальные триггеры высоты, используются в bottom sheet
 */
const RIDES = [
  {
    id: "zootopia-hot-pursuit",
    name: "Zootopia: Hot Pursuit",
    chineseName: "疯狂动物城：热力追踪",
    zone: "Zootopia",
    type: "Безрельсовый тёмный аттракцион",
    tags: ["indoor", "dark-ride"],
    durationMin: 5,
    minHeight: 81,
    heightFear: 2,
    fallFear: 3,
    thrill: 5,
    motionSickness: 3,
    stress: 3,
    avgWaitMin: 64,
    weekendWaitMin: 95,
    holidayWaitMin: 125,
    morningWaitMin: 20,
    eveningWaitMin: 30,
    rainStatus: "yes",
    rainNotes: "Полностью крытый павильон, работает в любой дождь без ограничений.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Максимальный",
    dpaValue: "Критическая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: true, darkness: true, rotation: true },
    description: "Самый новый аттракцион парка (открыт в декабре 2023): машинка-полицейский кар без рельсов мчится по Зверополису, спасая город от хаоса.",
    whyScaryOrSafe: "Машинка движется по плоскому полу на магнитной платформе. В сцене погони за вагонеткой на крыше наклон кабины и проекция создают иллюзию падения на 1–2 секунды, но это чисто визуальный эффект — реальной высоты нет вообще. Лучший выбор для акрофоба.",
    images: ["zootopia-1", "zootopia-2"]
  },
  {
    id: "tron-lightcycle",
    name: "TRON Lightcycle Power Run",
    chineseName: "创极速光轮",
    zone: "Tomorrowland",
    type: "Запускаемые горки на мотоциклах",
    tags: ["indoor", "outdoor", "coaster"],
    durationMin: 2,
    minHeight: 122,
    heightFear: 3,
    fallFear: 6,
    thrill: 9,
    motionSickness: 4,
    stress: 6,
    avgWaitMin: 48,
    weekendWaitMin: 90,
    holidayWaitMin: 120,
    morningWaitMin: 20,
    eveningWaitMin: 35,
    rainStatus: "partial",
    rainNotes: "Уличный участок накрыт герметичным куполом-навесом, поэтому обычно работает даже в сильный дождь; может временно останавливаться при грозе/молниях.",
    acrophobiaVerdict: "Скорее посетить",
    recommendation: "go",
    priority: "Максимальный",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "Флагман парка: разгон до ~95–100 км/ч на «мотоциклах» по подтверждённой трассе высотой 23,8 м (Roller Coaster Database), большая часть пути — в тёмном неоновом тоннеле.",
    whyScaryOrSafe: "Жёсткая фиксация ног и корпуса убирает ощущение «открытой кабины». Падений по высоте нет — только скорость. Уличный сегмент короткий и проходит под навесом, не видно неба. Главный фактор дискомфорта — интенсивность, не высота. Можно попросить обычное сиденье вместо «мотоцикла».",
    images: ["tron-1", "tron-2"]
  },
  {
    id: "soaring-over-the-horizon",
    name: "Soaring Over the Horizon",
    chineseName: "翱翔·飞越地平线",
    zone: "Adventure Isle",
    type: "4D симулятор полёта",
    tags: ["indoor"],
    durationMin: 5,
    minHeight: 102,
    heightFear: 7,
    fallFear: 4,
    thrill: 5,
    motionSickness: 5,
    stress: 7,
    avgWaitMin: 81,
    weekendWaitMin: 110,
    holidayWaitMin: 160,
    morningWaitMin: 45,
    eveningWaitMin: 55,
    rainStatus: "yes",
    rainNotes: "Полностью крытый зал, дождь не влияет на работу.",
    acrophobiaVerdict: "С осторожностью",
    recommendation: "caution",
    priority: "Высокий",
    dpaValue: "Экстремальная",
    flags: { hangingLegs: true, openCabin: true, visualHeight: true, fall: false, darkness: true, rotation: false },
    description: "Кресла поднимаются на 10–15 м перед гигантским вогнутым экраном с фильмом о полёте над горами, побережьями и городами мира.",
    whyScaryOrSafe: "Главный триггер парка для акрофобов: ноги свободно свисают, нет напольной опоры, а огромный экран усиливает иллюзию парения. Официальный сайт Shanghai Disney Resort прямо предупреждает, что людям с боязнью высоты или склонностью к укачиванию лучше не садиться. Если решитесь — просите нижний ряд (Row 3/C) и закрывайте глаза в горных сценах.",
    images: ["soaring-1", "soaring-2"]
  },
  {
    id: "seven-dwarfs-mine-train",
    name: "Seven Dwarfs Mine Train",
    chineseName: "七个小矮人矿山车",
    zone: "Fantasyland",
    type: "Семейные горки",
    tags: ["indoor", "outdoor", "coaster"],
    durationMin: 3,
    minHeight: 97,
    heightFear: 4,
    fallFear: 5,
    thrill: 5,
    motionSickness: 4,
    stress: 4,
    avgWaitMin: 68,
    weekendWaitMin: 100,
    holidayWaitMin: 150,
    morningWaitMin: 35,
    eveningWaitMin: 45,
    rainStatus: "partial",
    rainNotes: "Часть трассы на улице — обычно приостанавливается при сильном ливне или объявлении грозы, в лёгкий дождь работает.",
    acrophobiaVerdict: "Скорее посетить",
    recommendation: "go",
    priority: "Высокий",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: true, darkness: true, rotation: false },
    description: "Семейные горки с раскачивающимися вагонетками вокруг шахты гномов; максимальная высота трассы около 13 м.",
    whyScaryOrSafe: "Рельсы проложены по искусственному холму, окружённому скалами и деревьями — открытого вида «с края» нет. Спуски пологие, без зависания в невесомости. Вторая половина — крытая пещера. Хорошо подходит профилю «нормально переношу горки без ощущения высоты».",
    images: ["sdmt-1", "sdmt-2"]
  },
  {
    id: "pirates-of-the-caribbean",
    name: "Pirates of the Caribbean: Battle for the Sunken Treasure",
    chineseName: "加勒比海盗——沉落宝藏之战",
    zone: "Treasure Cove",
    type: "Тёмный лодочный аттракцион",
    tags: ["indoor", "dark-ride", "water"],
    durationMin: 7,
    minHeight: 81,
    heightFear: 1,
    fallFear: 3,
    thrill: 4,
    motionSickness: 2,
    stress: 2,
    avgWaitMin: 24,
    weekendWaitMin: 45,
    holidayWaitMin: 70,
    morningWaitMin: 10,
    eveningWaitMin: 15,
    rainStatus: "yes",
    rainNotes: "Полностью крытый павильон, отличный вариант на дождливый день.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Максимальный",
    dpaValue: "Умеренная",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: true, darkness: true, rotation: true },
    description: "Считается лучшей версией «Пиратов» в мире: лодки скользят по воде среди гигантских проекционных экранов, аниматроников Джека Воробья и Дэйви Джонса.",
    whyScaryOrSafe: "Лодка всё время остаётся на уровне водного зеркала бассейна. Единственный «спуск» — мягкий откат назад под небольшим углом в финале. Огромные изогнутые экраны визуально создают впечатление открытого пространства, но физической высоты нет вообще.",
    images: ["pirates-1", "pirates-2"]
  },
  {
    id: "roaring-rapids",
    name: "Roaring Rapids",
    chineseName: "雷鸣山漂流",
    zone: "Adventure Isle",
    type: "Сплав на рафтах",
    tags: ["outdoor", "water"],
    durationMin: 5,
    minHeight: 107,
    heightFear: 3,
    fallFear: 4,
    thrill: 6,
    motionSickness: 4,
    stress: 4,
    avgWaitMin: 54,
    weekendWaitMin: 80,
    holidayWaitMin: 100,
    morningWaitMin: 20,
    eveningWaitMin: 25,
    rainStatus: "no",
    rainNotes: "Закрывается при грозе и штормовом предупреждении; в обычный дождь может работать, но вы и так промокнете дополнительно.",
    acrophobiaVerdict: "По желанию",
    recommendation: "caution",
    priority: "Средний",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: true, visualHeight: false, fall: true, darkness: true, rotation: true },
    description: "Круглый плот плывёт по бурной реке через пещеру с гигантским аниматроником Q'aráq, неизбежны брызги.",
    whyScaryOrSafe: "Плот движется по воде на уровне земли в открытых бортах — ощущение высоты минимально, короткий подъём в начале не пугающий. Главный риск для акрофоба не высота, а внезапность и брызги. Возьмите дождевик.",
    images: ["rapids-1", "rapids-2"]
  },
  {
    id: "rexs-racer",
    name: "Rex’s Racer",
    chineseName: "抱抱龙冲天赛车",
    zone: "Toy Story Land",
    type: "Реверсивные горки-полупайп",
    tags: ["outdoor", "coaster"],
    durationMin: 1.5,
    minHeight: 120,
    heightFear: 8,
    fallFear: 8,
    thrill: 8,
    motionSickness: 5,
    stress: 7,
    avgWaitMin: 50,
    weekendWaitMin: 90,
    holidayWaitMin: 115,
    morningWaitMin: 25,
    eveningWaitMin: 35,
    rainStatus: "no",
    rainNotes: "Закрывается даже при лёгком дожде — открытый трек скользкий, автоматика блокирует запуск.",
    acrophobiaVerdict: "Лучше пропустить",
    recommendation: "skip",
    priority: "Средний",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: true, visualHeight: true, fall: true, darkness: false, rotation: false },
    description: "U-образный полупайп: поезд разгоняется вперёд-назад, взлетая почти вертикально на высоту около 25 м.",
    whyScaryOrSafe: "На верхних точках пассажиры на долю секунды зависают лицом вниз к земле в состоянии, близком к невесомости. Кабина открытая, борта невысокие, реальная высота полностью видна. Одна из худших комбинаций для акрофоба: открытая кабина + видимое падение + отсутствие декораций, скрывающих высоту.",
    images: ["rex-1", "rex-2"]
  },
  {
    id: "challenge-trails",
    name: "Challenge Trails at Camp Discovery",
    chineseName: "古迹探索营",
    zone: "Adventure Isle",
    type: "Верёвочный курс на высоте",
    tags: ["outdoor", "walk-through"],
    durationMin: 25,
    minHeight: 106,
    heightFear: 9,
    fallFear: 8,
    thrill: 7,
    motionSickness: 2,
    stress: 9,
    avgWaitMin: 25,
    weekendWaitMin: 35,
    holidayWaitMin: 46,
    morningWaitMin: 12,
    eveningWaitMin: 18,
    rainStatus: "no",
    rainNotes: "Закрывается мгновенно при дожде или ветре — намокшие верёвки и доски слишком скользкие.",
    acrophobiaVerdict: "Лучше пропустить",
    recommendation: "skip",
    priority: "Низкий",
    dpaValue: "Средняя",
    flags: { hangingLegs: false, openCabin: true, visualHeight: true, fall: false, darkness: false, rotation: false },
    description: "Три верёвочных и скальных маршрута разного уровня сложности вдоль отвесных скал Гремящей горы, со страховкой на верхнем рельсе.",
    whyScaryOrSafe: "Это настоящая высота над землёй: узкие качающиеся доски, тросы и металлические штыри прямо над ущельем реки, без сплошных бортов или сетки. Страховка не убирает визуальный контакт с обрывом. Самый высотный по ощущениям объект парка — для тяжёлой акрофобии противопоказан.",
    images: ["camp-1", "camp-2"]
  },
  {
    id: "jet-packs",
    name: "Jet Packs",
    chineseName: "喷气背包飞行器",
    zone: "Tomorrowland",
    type: "Воздушная карусель",
    tags: ["outdoor"],
    durationMin: 1.5,
    minHeight: 112,
    heightFear: 7,
    fallFear: 4,
    thrill: 5,
    motionSickness: 5,
    stress: 6,
    avgWaitMin: 35,
    weekendWaitMin: 50,
    holidayWaitMin: 60,
    morningWaitMin: 17,
    eveningWaitMin: 22,
    rainStatus: "no",
    rainNotes: "Закрывается при дожде и сильном ветре — открытые кабины и электроника.",
    acrophobiaVerdict: "С осторожностью",
    recommendation: "caution",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: true, openCabin: true, visualHeight: true, fall: false, darkness: false, rotation: true },
    description: "Кабины на вращающихся рычагах вокруг центральной «энергосферы»; единственный в парке аттракцион с по-настоящему свисающими ногами на открытом воздухе.",
    whyScaryOrSafe: "Кабина консольная, без напольной опоры, центробежная сила отклоняет её наружу и вверх. НО пассажир сам управляет высотой джойстиком — можно держать кабину низко и ровно, что заметно снижает дискомфорт.",
    images: ["jetpacks-1", "jetpacks-2"]
  },
  {
    id: "peter-pans-flight",
    name: "Peter Pan’s Flight",
    chineseName: "小飞侠天空奇遇",
    zone: "Fantasyland",
    type: "Подвесной тёмный аттракцион",
    tags: ["indoor", "dark-ride"],
    durationMin: 3,
    minHeight: 0,
    heightFear: 3,
    fallFear: 2,
    thrill: 2,
    motionSickness: 2,
    stress: 2,
    avgWaitMin: 31,
    weekendWaitMin: 55,
    holidayWaitMin: 70,
    morningWaitMin: 12,
    eveningWaitMin: 18,
    rainStatus: "yes",
    rainNotes: "Полностью крытый, работает в любой дождь.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Очень высокий",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "Кораблики-пираты «летят» на подвесном рельсе под потолком павильона над миниатюрным ночным Лондоном и Нетландией.",
    whyScaryOrSafe: "Физическая высота кораблика над полом не превышает ~2,5 м, пол замаскирован темнотой и светящимися макетами. Движение плавное, без рывков и наклонов. Иллюзия полёта милая, а не пугающая — отличный выбор для акрофоба.",
    images: ["peterpan-1", "peterpan-2"]
  },
  {
    id: "voyage-crystal-grotto",
    name: "Voyage to the Crystal Grotto",
    chineseName: "晶彩奇航",
    zone: "Fantasyland",
    type: "Прогулочный лодочный тур",
    tags: ["outdoor", "water"],
    durationMin: 7,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 20,
    weekendWaitMin: 40,
    holidayWaitMin: 55,
    morningWaitMin: 10,
    eveningWaitMin: 15,
    rainStatus: "partial",
    rainNotes: "Частично открытый канал — комфортно в лёгкий дождь, может приостанавливаться при сильном ливне.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Высокий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "Спокойный заплыв на лодках по открытым каналам, в финале — заезд в грот под центральным замком со световым шоу.",
    whyScaryOrSafe: "Полностью равнинный водный маршрут без перепадов высоты. Эксклюзив Шанхая, особенно красив вечером с подсветкой замка.",
    images: ["grotto-1", "grotto-2"]
  },
  {
    id: "winnie-the-pooh",
    name: "The Many Adventures of Winnie the Pooh",
    chineseName: "小熊维尼历险记",
    zone: "Fantasyland",
    type: "Семейный тёмный аттракцион",
    tags: ["indoor", "dark-ride"],
    durationMin: 4,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 2,
    motionSickness: 2,
    stress: 1,
    avgWaitMin: 31,
    weekendWaitMin: 50,
    holidayWaitMin: 60,
    morningWaitMin: 12,
    eveningWaitMin: 17,
    rainStatus: "yes",
    rainNotes: "Полностью крытый, работает в любой дождь.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Средний",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "«Горшочки с мёдом» катятся по утопленному в пол рельсу через мир Винни-Пуха.",
    whyScaryOrSafe: "Никаких перепадов высоты, мягкая тёмная сказочная атмосфера. Полностью безопасно для акрофоба.",
    images: ["pooh-1", "pooh-2"]
  },
  {
    id: "buzz-lightyear",
    name: "Buzz Lightyear Planet Rescue",
    chineseName: "巴斯光年星际营救",
    zone: "Tomorrowland",
    type: "Интерактивный тёмный тир",
    tags: ["indoor", "dark-ride"],
    durationMin: 4,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 2,
    motionSickness: 3,
    stress: 2,
    avgWaitMin: 11,
    weekendWaitMin: 20,
    holidayWaitMin: 25,
    morningWaitMin: 5,
    eveningWaitMin: 8,
    rainStatus: "yes",
    rainNotes: "Полностью крытый, работает в любой дождь.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Средний",
    dpaValue: "Низкая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: true },
    description: "Вагонетки скользят по ровной колее в космическом павильоне — нужно стрелять по мишеням и набирать очки.",
    whyScaryOrSafe: "Движение строго по полу, никакой высоты. Хорошая «передышка» между интенсивными аттракционами и почти всегда короткая очередь.",
    images: ["buzz-1", "buzz-2"]
  },
  {
    id: "dumbo",
    name: "Dumbo the Flying Elephant",
    chineseName: "小飞象",
    zone: "Gardens of Imagination",
    type: "Воздушная карусель",
    tags: ["outdoor"],
    durationMin: 2,
    minHeight: 0,
    heightFear: 2,
    fallFear: 1,
    thrill: 2,
    motionSickness: 4,
    stress: 3,
    avgWaitMin: 31,
    weekendWaitMin: 50,
    holidayWaitMin: 62,
    morningWaitMin: 12,
    eveningWaitMin: 17,
    rainStatus: "no",
    rainNotes: "Открытая карусель — закрывается в дождь.",
    acrophobiaVerdict: "По желанию",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Умеренная",
    flags: { hangingLegs: false, openCabin: true, visualHeight: true, fall: false, darkness: false, rotation: true },
    description: "Классические летающие слоники поднимаются на высоту до ~5 м над садами.",
    whyScaryOrSafe: "Кабина открытая, но есть индивидуальный рычаг управления — можно держать слоника у самой земли всю поездку.",
    images: ["dumbo-1", "dumbo-2"]
  },
  {
    id: "slinky-dog-spin",
    name: "Slinky Dog Spin",
    chineseName: "弹簧狗团团转",
    zone: "Toy Story Land",
    type: "Волнообразная карусель",
    tags: ["outdoor"],
    durationMin: 2,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 2,
    motionSickness: 4,
    stress: 2,
    avgWaitMin: 25,
    weekendWaitMin: 40,
    holidayWaitMin: 49,
    morningWaitMin: 12,
    eveningWaitMin: 17,
    rainStatus: "no",
    rainNotes: "Открытый аттракцион — приостанавливается в дождь.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: true },
    description: "Поезд-пружинка катится по кольцевому треку с мягкими волнообразными перепадами до 1,5 м.",
    whyScaryOrSafe: "Перепады незначительные, посадка глубокая. Высотных триггеров нет.",
    images: ["slinky-1", "slinky-2"]
  },
  {
    id: "woodys-roundup",
    name: "Woody’s Roundup",
    chineseName: "胡迪牛仔嘉年华",
    zone: "Toy Story Land",
    type: "Вращающиеся вагонетки",
    tags: ["outdoor"],
    durationMin: 1.5,
    minHeight: 81,
    heightFear: 1,
    fallFear: 1,
    thrill: 3,
    motionSickness: 5,
    stress: 3,
    avgWaitMin: 24,
    weekendWaitMin: 45,
    holidayWaitMin: 65,
    morningWaitMin: 12,
    eveningWaitMin: 20,
    rainStatus: "no",
    rainNotes: "Открытая площадка — приостанавливается в дождь.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Высокая",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: true },
    description: "Стилизованные повозки движутся по траектории «восьмёрки» строго в горизонтальной плоскости.",
    whyScaryOrSafe: "Перепадов высоты нет совсем, только резкие боковые заносы. Полностью безопасно для акрофоба.",
    images: ["woody-1", "woody-2"]
  },
  {
    id: "hunny-pot-spin",
    name: "Hunny Pot Spin",
    chineseName: "旋转疯蜜罐",
    zone: "Fantasyland",
    type: "Вращающиеся чашки",
    tags: ["outdoor"],
    durationMin: 1.5,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 3,
    motionSickness: 7,
    stress: 3,
    avgWaitMin: 15,
    weekendWaitMin: 30,
    holidayWaitMin: 41,
    morningWaitMin: 8,
    eveningWaitMin: 12,
    rainStatus: "no",
    rainNotes: "Открытая площадка — приостанавливается в дождь.",
    acrophobiaVerdict: "По желанию",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: true },
    description: "Классическая карусель на уровне земли — «горшочки с мёдом» вращаются на горизонтальных дисках.",
    whyScaryOrSafe: "Высоты нет вообще, но интенсивное вращение может вызвать сильное укачивание — учитывайте это отдельно от страха высоты.",
    images: ["hunnypot-1", "hunnypot-2"]
  },
  {
    id: "fantasia-carousel",
    name: "Fantasia Carousel",
    chineseName: "幻想曲旋转木马",
    zone: "Gardens of Imagination",
    type: "Классическая карусель",
    tags: ["outdoor"],
    durationMin: 2,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 2,
    stress: 1,
    avgWaitMin: 22,
    weekendWaitMin: 35,
    holidayWaitMin: 44,
    morningWaitMin: 8,
    eveningWaitMin: 15,
    rainStatus: "no",
    rainNotes: "Открытая карусель — закрывается в дождь.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: true },
    description: "Двухъярусная классическая карусель с лошадками на плоской платформе.",
    whyScaryOrSafe: "Вертикальные колебания в пределах метра — абсолютно безопасно для акрофоба.",
    images: ["fantasia-1", "fantasia-2"]
  },
  {
    id: "explorer-canoes",
    name: "Explorer Canoes",
    chineseName: "探险家独木舟",
    zone: "Treasure Cove",
    type: "Весельный заплыв",
    tags: ["outdoor", "water"],
    durationMin: 10,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 2,
    motionSickness: 2,
    stress: 2,
    avgWaitMin: 27,
    weekendWaitMin: 35,
    holidayWaitMin: 42,
    morningWaitMin: 12,
    eveningWaitMin: 20,
    rainStatus: "no",
    rainNotes: "Закрывается при первых каплях дождя.",
    acrophobiaVerdict: "Скорее посетить",
    recommendation: "go",
    priority: "Средний",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: false },
    description: "Гости сами гребут вёслами на открытых каноэ вокруг острова Adventure Isle под руководством инструктора.",
    whyScaryOrSafe: "Высотных факторов нет, требуется умеренная физическая активность.",
    images: ["canoes-1", "canoes-2"]
  },
  {
    id: "once-upon-a-time",
    name: "“Once Upon a Time” Adventure",
    chineseName: "漫游童话时光",
    zone: "Fantasyland",
    type: "Пешеходная галерея в замке",
    tags: ["indoor", "walk-through"],
    durationMin: 12,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 11,
    weekendWaitMin: 20,
    holidayWaitMin: 25,
    morningWaitMin: 5,
    eveningWaitMin: 8,
    rainStatus: "yes",
    rainNotes: "Внутри замка, полностью защищено от дождя.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Средний",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "Интерактивная прогулка по залам замка с голограммами и проекциями сказки о Белоснежке.",
    whyScaryOrSafe: "Несмотря на подъём по лестницам внутри замка, все переходы закрыты капитальными стенами без панорамных окон — высота не визуализируется.",
    images: ["onceupon-1", "onceupon-2"]
  },
  {
    id: "alice-maze",
    name: "Alice in Wonderland Maze",
    chineseName: "爱丽丝梦游仙境迷宫",
    zone: "Fantasyland",
    type: "Пешеходный лабиринт",
    tags: ["outdoor", "walk-through"],
    durationMin: 15,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 5,
    weekendWaitMin: 5,
    holidayWaitMin: 10,
    morningWaitMin: 5,
    eveningWaitMin: 5,
    rainStatus: "partial",
    rainNotes: "Открытые тропинки могут быть мокрыми, но в лёгкий дождь доступен.",
    acrophobiaVerdict: "По желанию",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: false },
    description: "Прогулочный лабиринт из живых изгородей с искажающими зеркалами и интерактивными воротами.",
    whyScaryOrSafe: "Дорожки на уровне земли, мостики с высокими сплошными ограждениями — высоты нет.",
    images: ["alice-1", "alice-2"]
  },
  {
    id: "vista-trail",
    name: "Vista Trail at Camp Discovery",
    chineseName: "古迹探索营的探索步行道",
    zone: "Adventure Isle",
    type: "Пешеходная обзорная тропа",
    tags: ["outdoor", "walk-through"],
    durationMin: 15,
    minHeight: 0,
    heightFear: 2,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 17,
    weekendWaitMin: 17,
    holidayWaitMin: 17,
    morningWaitMin: 8,
    eveningWaitMin: 10,
    rainStatus: "partial",
    rainNotes: "Наземная тропа — обычно открыта в лёгкий дождь, закрывается вместе с верёвочным курсом при ливне.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: false },
    description: "Наземная тропа у подножия Гремящей горы — альтернатива верёвочному курсу Challenge Trails с видом на водопады и пещеры.",
    whyScaryOrSafe: "Идеальная замена Challenge Trails для акрофоба: те же декорации, но без подъёма над землёй.",
    images: ["vista-1", "vista-2"]
  },
  {
    id: "sirens-revenge",
    name: "Siren’s Revenge",
    chineseName: "探秘海妖复仇号",
    zone: "Treasure Cove",
    type: "Интерактивный корабль-музей",
    tags: ["outdoor", "walk-through"],
    durationMin: 10,
    minHeight: 0,
    heightFear: 2,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 5,
    weekendWaitMin: 5,
    holidayWaitMin: 5,
    morningWaitMin: 5,
    eveningWaitMin: 5,
    rainStatus: "partial",
    rainNotes: "Открытая палуба — комфортно при наличии зонта/дождевика.",
    acrophobiaVerdict: "По желанию",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: false },
    description: "Пиратский галеон у пристани Treasure Cove, можно свободно исследовать палубы, каюты и трюмы.",
    whyScaryOrSafe: "Высокие прочные деревянные борта судна полностью исключают ощущение открытой высоты.",
    images: ["siren-1", "siren-2"]
  },
  {
    id: "shipwreck-shore",
    name: "Shipwreck Shore",
    chineseName: "船奇戏水滩",
    zone: "Treasure Cove",
    type: "Водная игровая площадка",
    tags: ["outdoor", "water"],
    durationMin: 15,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 5,
    weekendWaitMin: 5,
    holidayWaitMin: 5,
    morningWaitMin: 5,
    eveningWaitMin: 5,
    rainStatus: "no",
    rainNotes: "Водная площадка приятна в жару, но в дождь не имеет смысла (и часто отключают фонтаны).",
    acrophobiaVerdict: "По желанию",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: false },
    description: "Детская игровая зона с водными пушками и декорациями обломков корабля.",
    whyScaryOrSafe: "Полностью на уровне земли, высотных триггеров нет.",
    images: ["shipwreck-1", "shipwreck-2"]
  },
  {
    id: "space-chat-stitch",
    name: "Space Chat with Stitch",
    chineseName: "太空对话史迪奇",
    zone: "Tomorrowland",
    type: "Интерактивное шоу",
    tags: ["indoor", "show"],
    durationMin: 15,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 16,
    weekendWaitMin: 20,
    holidayWaitMin: 24,
    morningWaitMin: 8,
    eveningWaitMin: 12,
    rainStatus: "yes",
    rainNotes: "Полностью крытый театральный зал.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "Живое интерактивное общение зрителей с цифровым анимированным Стичем в реальном времени.",
    whyScaryOrSafe: "Сидячее шоу без движения, отличная пауза в дождь.",
    images: ["stitch-1", "stitch-2"]
  },
  {
    id: "tron-realm",
    name: "TRON Realm, Chevrolet Digital Challenge",
    chineseName: "创界：雪佛兰数字挑战",
    zone: "Tomorrowland",
    type: "Интерактивный павильон",
    tags: ["indoor"],
    durationMin: 15,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 2,
    motionSickness: 2,
    stress: 1,
    avgWaitMin: 12,
    weekendWaitMin: 15,
    holidayWaitMin: 18,
    morningWaitMin: 5,
    eveningWaitMin: 10,
    rainStatus: "yes",
    rainNotes: "Полностью крытый, отличный вариант на дождливый день.",
    acrophobiaVerdict: "По желанию",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: true, rotation: false },
    description: "Виртуальные гонки и симуляторы в мире TRON, без физических движений.",
    whyScaryOrSafe: "Все экспонаты на плоском полу выставочного павильона.",
    images: ["tronrealm-1", "tronrealm-2"]
  },
  {
    id: "marvel-universe",
    name: "Marvel Universe (+ Become Iron Man)",
    chineseName: "漫威英雄总部",
    zone: "Gardens of Imagination",
    type: "Выставочно-интерактивный павильон",
    tags: ["indoor", "walk-through"],
    durationMin: 20,
    minHeight: 0,
    heightFear: 1,
    fallFear: 1,
    thrill: 1,
    motionSickness: 1,
    stress: 1,
    avgWaitMin: 5,
    weekendWaitMin: 6,
    holidayWaitMin: 6,
    morningWaitMin: 5,
    eveningWaitMin: 5,
    rainStatus: "yes",
    rainNotes: "Полностью крытый павильон.",
    acrophobiaVerdict: "Обязательно посетить",
    recommendation: "go",
    priority: "Низкий",
    dpaValue: "Отсутствует",
    flags: { hangingLegs: false, openCabin: false, visualHeight: false, fall: false, darkness: false, rotation: false },
    description: "Встречи с супергероями, выставка и виртуальная примерка костюма Железного Человека (Become Iron Man).",
    whyScaryOrSafe: "Полностью безопасно с точки зрения высоты, без физических движений.",
    images: ["marvel-1", "marvel-2"]
  }
];

const RESTAURANTS = [
  {
    id: "barbossas-bounty",
    name: "Barbossa’s Bounty",
    zone: "Treasure Cove",
    rainFriendly: true,
    longStay: true,
    whatToOrder: "Барбекю-рёбра и курица, открытая кухня-гриль",
    bestTime: "Сразу после Pirates of the Caribbean, на обед 12:00–13:00",
    why: "Самый просторный крытый ресторан парка, окна с видом на лодки Pirates — можно отдыхать долго, не теряя атмосферу."
  },
  {
    id: "wandering-moon-teahouse",
    name: "Wandering Moon Teahouse",
    zone: "Gardens of Imagination / Fantasyland",
    rainFriendly: true,
    longStay: true,
    whatToOrder: "Согревающие супы, чай, традиционные китайские блюда",
    bestTime: "В затяжной дождь, в любое время дня",
    why: "Тихий зал в стиле усадеб Сучжоу — лучшее убежище для долгого ожидания непогоды."
  },
  {
    id: "stargazer-grill",
    name: "Stargazer Grill",
    zone: "Tomorrowland",
    rainFriendly: true,
    longStay: true,
    whatToOrder: "Бургеры с говядиной вагю",
    bestTime: "После TRON или Buzz Lightyear, ужин 18:30–19:30",
    why: "Большой выбор блюд и удобное расположение рядом с топ-аттракционами Tomorrowland."
  },
  {
    id: "pinocchio-village-kitchen",
    name: "Pinocchio Village Kitchen",
    zone: "Fantasyland",
    rainFriendly: true,
    longStay: false,
    whatToOrder: "Пицца и паста в итальянском стиле",
    bestTime: "Обед между Seven Dwarfs и Peter Pan’s Flight",
    why: "Удобная быстрая остановка в центре Fantasyland без потери темпа маршрута."
  },
  {
    id: "royal-banquet-hall",
    name: "Royal Banquet Hall",
    zone: "Внутри замка, Fantasyland",
    rainFriendly: true,
    longStay: true,
    whatToOrder: "Сет-меню с встречей персонажей (нужна бронь заранее)",
    bestTime: "Обед или ужин по предварительной брони",
    why: "Большой крытый банкетный зал внутри замка — надёжное укрытие от любого дождя плюс шоу с персонажами."
  },
  {
    id: "mickey-pals-market-cafe",
    name: "Mickey & Pals Market Café",
    zone: "Mickey Avenue",
    rainFriendly: true,
    longStay: false,
    whatToOrder: "Фастфуд американского стиля, сэндвичи, салаты",
    bestTime: "Перед выходом из парка или в начале дня",
    why: "Близко к входу — удобно перед началом или в конце маршрута, под крышей торговой улицы."
  }
];

const EVENING_SHOW = {
  name: "ILLUMINATE! A Nighttime Celebration",
  where: "Центральная аллея у замка Enchanted Storybook Castle",
  claimSpotMin: 40,
  rainPolicy: "Лёгкий дождь обычно не отменяет шоу; при грозе/сильном ливне шоу может быть отменено или сокращено — проверяйте статус в приложении в день визита.",
  backupIndoor: ["Frozen: A Sing-Along Celebration", "Eye of the Storm: Captain Jack’s Stunt Spectacular", "Mickey’s Storybook Adventure"],
  disclaimer: "Актуальное расписание и статус шоу нужно проверить в официальном приложении Shanghai Disney Resort в день посещения."
};

const DPA_INFO = {
  intro: "Disney Premier Access (DPA) — платная система скип-лайн в Shanghai Disneyland. Покупается через официальное приложение прямо в день визита, не привязана к временному окну (можно использовать в любое время дня).",
  priceNote: "Ориентировочно от ~140 юаней за один аттракцион; есть бандлы на несколько аттракционов и Deluxe-пакет с Early Park Entry. Цены нужно проверять в приложении — они могут отличаться по сезону.",
  highPriority: [
    { id: "zootopia-hot-pursuit", note: "Покупайте первым — разбирают быстрее, чем DPA на TRON." },
    { id: "soaring-over-the-horizon", note: "Высокая эффективность, но для акрофоба — только если решили рискнуть." },
    { id: "seven-dwarfs-mine-train", note: "Очередь стабильно одна из самых длинных в парке." },
    { id: "tron-lightcycle", note: "DPA экономит до 90+ минут в выходные." }
  ],
  weatherDependent: [
    { id: "roaring-rapids", note: "Берите DPA только если погода точно позволит — при грозе аттракцион закроется и доступ не вернут." }
  ],
  lowPriority: [
    { id: "peter-pans-flight", note: "Очередь умеренная, DPA полезен в основном в выходные и праздники." }
  ],
  notNeeded: "На детские карусели, спиннеры, шоу и walk-through аттракционы (Dumbo, Fantasia Carousel, Marvel Universe, Once Upon a Time Adventure и т.п.) DPA не нужен — очередь и так короткая.",
  rainAdvice: "В дождь очереди резко падают почти везде, особенно на улице. DPA стоит брать только на крытые топ-аттракционы (Zootopia, TRON, Pirates, Soaring) — и даже тогда сначала проверьте живую очередь в приложении: в дождливый будний день она часто и так короткая."
};
